### PR TITLE
Fix: Side panel data not updating when different user cards are clicked

### LINKED ISSUE #899: Bug: Side Panel Data Not Changing When Different User Cards are Clicked
### Issue Description

The side panel on the user dashboard does not update to display the selected user's data when a user clicks on a different user card. It only shows the information of the first user in the list by default.

### Expected Behavior

When a user clicks on any user card, the side panel should dynamically update to display the corresponding user's information. This will ensure that users can view detailed information about the selected user seamlessly.

### Current Behavior

- When the page loads, the side panel displays the data of the first user in the list.
- Clicking on any other user card does not change the displayed information in the side panel.
### Screenshots

rq4ZQsU

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Navigate to this [dashboard page](https://dashboard.realdevsquad.com/users/discord/?tab=in_discord).
2. Observe that the side panel displays the first user's data.
3. Click on any other user card.
4. Notice that the side panel does not change to reflect the new selection.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by AnujChhikara**
Date: 24 Oct 2024

Developer Name: Anuj Chhikara (anuj-chhikara-1)

---

## Issue Ticket Number

- Closed #899 
## Description

This PR resolves an issue where the side panel failed to update when selecting different user cards. Previously, the side panel always displayed data from the initially selected user, regardless of subsequent selections, leading to outdated information and impacting user navigation.
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

brave_pbwdpUkSbY
</details>

## Test Coverage
<details>
<summary>Change File Tests</summary>

image

</details>
<details>
<summary>Complete Tests</summary>

image

</details>

## Additional Notes

To address the issue of production API calls during test runs, I have added the following conditional code in the utils module:
```javascript
const API_BASE_URL =
  window.location.hostname === 'localhost'
    ? 'https://staging-api.realdevsquad.com'
    : window.API_BASE_URL;

``` 
### Why This Change?

Before this update, tests were unintentionally hitting the production API. By adding this code, we ensure that only the staging API is called when tests run on this file. This setup also allows for mock data to be returned conditionally as needed, making tests more reliable and isolated from live data.

We already using this code in other script also for reference attaching image

### CODE REVIEW

File: users/discord/App.js [hunk 1]
```diff
@@ -37,16 +37,16 @@ const handleTabNavigation = async (e) => {
...
-  const selectedUserId =
-    e.target?.getAttribute('data_key') ||
-    e.target.parentElement?.getAttribute('data_key');
-
-  if (selectedUserId) {
-    showUser = usersData[activeTab]?.findIndex(
-      (user) => user.id === selectedUserId,
+const handleUserSelected = (userId) => {
+  if (userId) {
+    const selectedIndex = usersData[activeTab]?.findIndex(
```
Comment (pankajjs) [inline users/discord/App.js:42]: Can we use selectedUserIndex?

File: users/discord/App.js
Comment (vinit717) [inline users/discord/App.js:1]: Can you write the test for your changes

Comment (AnujChhikara) [reply users/discord/App.js:1]: added

**Comment by shubhdevelop** [comment]
Add the Screenshot of the test coverage that you added, not the success of all the test case

File: __tests__/users/App.test.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 const puppeteer = require('puppeteer');
 const { filteredUsersData } = require('../../mock-data/users');
 const { mockUserData } = require('../../mock-data/users/mockdata');
-const API_BASE_URL = 'https://staging-api.realdevsquad.com';
+const API_BASE_URL = 'https://api.realdevsquad.com';
```
Comment (shubhdevelop) [inline __tests__/users/App.test.js:4]: why we changing base URL?

File: __tests__/users/App.test.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 const puppeteer = require('puppeteer');
 const { filteredUsersData } = require('../../mock-data/users');
 const { mockUserData } = require('../../mock-data/users/mockdata');
-const API_BASE_URL = 'https://staging-api.realdevsquad.com';
```
Comment (pankajjs) [inline __tests__/users/App.test.js:4]: Why did you. change this?

**Comment by shubhdevelop** [comment]
Add PR Description, of what changed

File: __tests__/users/App.test.js (hunk 3 above)
Comment (AnujChhikara) [reply __tests__/users/App.test.js:4]: Testing runs on localhost:8000 and in the loadENV file we have declared this
```javascript
window.API_BASE_URL = 'https://api.realdevsquad.com';

if (
  window.location.hostname !== 'dashboard.realdevsquad.com' &&
  window.location.hostname !== 'localhost'
) {
  window.API_BASE_URL = 'https://staging-api.realdevsquad.com';
}
``` 
- Since the condition for switching to the staging API (https://staging-api.realdevsquad.com) only applies if the hostname is not dashboard.realdevsquad.com or localhost, testing on localhost will default to the production API (https://api.realdevsquad.com).
- After inspecting the API calls made during testing, you can confirm that no staging API requests are being sent. To provide controlled data responses for specific requests, you’ll need to adjust the base URL in the intercept function. This allows you to mock API responses directly within the test file when needed.

**Review by pankajjs — APPROVED** [review]

**Review by vinit717 — APPROVED** [review]
