### PR TITLE
Restrict approve and reject buttons on the Task Request detail page to super_user only

### LINKED ISSUE #885: Restrict 'Approve' and 'Reject' Buttons to Super Users in Task Request Page
### Issue Description

When a user shares the TCR link, all members are able to view the task. However, members who are not super_users can also see the "Approve" and "Reject" buttons, which should only be visible to super_users.

### Expected Behavior

Only super_users should be able to see and interact with the "Approve" and "Reject" buttons when viewing a task in the dashboard. Regular members should not have access to these buttons
### Current Behavior

All members, including non-super_users, can see the "Approve" and "Reject" buttons when viewing a task, which could lead to  confusion.
### Screenshots
 
Selection_002

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1.  Navigate to anyone tcr link
2.  Anyone can see the reject/approve button there

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by AnujChhikara**
Date: 19 Oct 2024

Developer Name: Anuj Chhikara (anuj-chhikara-1)

---

## Issue Ticket Number

- Closes #885 
## Description

- This PR ensures that only **super users** can see the **Approve** and **Reject** buttons on the task request page.
- Modified the task request page to conditionally render the **Approve** and **Reject** buttons.
- These buttons will now only appear if the logged-in user has the `super_user` role.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Updated Page</summary>

image

</details>

<details>
<summary>Buttons Working</summary>

brave_or3zX6Q2UM
brave_fh9SC9Nvll

</details>

<details>
<summary>Feature Flag</summary>

brave_5kVwwDtH5X

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Screenshot from 2024-10-20 10-55-42
</details>

### CODE REVIEW

**Review by iamitprakash — CHANGES_REQUESTED** [review]
coverage seems low

File: task-requests/details/script.js [hunk 1]
```diff
@@ -410,14 +436,17 @@ const renderGithubIssue = async () => {
   );
 };
 const renderRejectButton = (taskRequest) => {
+  if (self_user.roles['super_user']) {
+    rejectButton.classList.remove('hidden');
+  }
```
Comment (Achintya-Chatterjee) [inline task-requests/details/script.js:441]: both the `reject` and `approve` buttons should follow the same role-based logic, where they are hidden or shown based on whether the user is a superuser.

File: task-requests/details/script.js [hunk 2]
```diff
@@ -200,17 +214,26 @@ async function updateTaskRequest(action, userId) {
   }
 }
 
-function getActionButton(requestor) {
+function getActionButton(requestor, taskRequest) {
+  const isSuperUser = self_user.roles['super_user'];
```
Comment (Achintya-Chatterjee) [inline task-requests/details/script.js:218]: the checks for superuser roles appear in multiple places in the codebases (e.g., in `getActionButton`, and `renderRejectButton`). This could lead to maintenance issues down the road.

We can consider abstracting role checks into a utility function like `isSuperUser()` to make it easier to handle role logic across our codebase.

File: task-requests/details/script.js [hunk 3]
```diff
@@ -200,17 +214,26 @@ async function updateTaskRequest(action, userId) {
...
+  if (!isSuperUser) {
+    return createCustomElement({
+      tagName: 'p',
+      textContent:
+        taskRequest.status[0].toUpperCase() +
+        taskRequest.status.slice(1).toLowerCase(),
+      class: ['requestors__container__list__status'],
+    });
+  }
+
```
[the remark this answers is not in the document]
Comment (AnujChhikara) [reply task-requests/details/script.js]: Sir, fallback logic is there if user is not super_we just render the task status as you can see on like 219 we check if not super_use then we render the task status.

File: task-requests/details/script.js (hunk 1 above)
Comment (AnujChhikara) [reply task-requests/details/script.js]: to make the user experience better i added the hidden class to the reject button initially and when the ui render we check if user is super_user then only remove the hidden class otherwise no need to show the reject button to the normal member

File: task-requests/details/script.js [hunk 4]
```diff
@@ -4,6 +4,7 @@ const API_BASE_URL =
     : window.API_BASE_URL;
 
 let taskRequest;
+let self_user;
```
[the remark this answers is not in the document]
Comment (AnujChhikara) [reply task-requests/details/script.js]: sorry about that will take care of it from now

File: task-requests/details/script.js (hunk 2 above)
Comment (AnujChhikara) [reply task-requests/details/script.js]: Sir. i have added a function that check the role

File: task-requests/details/index.html [hunk 5]
```diff
@@ -86,7 +86,10 @@ <h4 class="requestors__container__title">Requestors</h4>
           </div>
         </div>
         <div class="reject__container">
-          <button id="reject-button" class="request-details__reject__button">
+          <button
+            id="reject-button"
+            class="request-details__reject__button hidden"
+          >
```
Comment (yesyash) [inline task-requests/details/index.html:92]: - is the reject button not conditionally rendered?

File: task-requests/details/script.js [hunk 6]
```diff
@@ -23,6 +24,23 @@ const errorMessage =
...
+    method: 'GET',
+    credentials: 'include',
+    headers: {
+      'Content-type': 'application/json',
+    },
+  });
+
+  const self_user = await res.json();
+  return self_user;
+}
```
Comment (yesyash) [inline task-requests/details/script.js:38]: - i think a function to call `users/self` is already present as it is called after the user logs in, see if you can use it.

**Review by yesyash — CHANGES_REQUESTED** [review]

File: task-requests/details/index.html (hunk 5 above)
Comment (AnujChhikara) [reply task-requests/details/index.html:92]: By default, the **Reject Button** has a `hidden` class. The function below removes the `hidden` class only if:  
1. The **user is a superuser**.  


- If the conditions are not met, the button remains hidden.
- Yes, It wil be part of the dom to avoids unnecessary DOM manipulation. If needed i can  create the button dynamically
### Code

```javascript
const renderRejectButton = (taskRequest) => {
  // Exit if the user is not a superuser.
  if (!isSuperUser) return;

  // Show or hide the reject button based on the task request status.
  if (taskRequest?.status === 'PENDING') {
    rejectButton.classList.remove('hidden');
  } else if (!rejectButton.classList.contains('hidden')) {
    rejectButton.classList.add('hidden');
  }

  // Handle the button click event to reject the task request.
  rejectButton.addEventListener('click', async () => {
    const res = await updateTaskRequest(TaskRequestAction.REJECT);
    if (res?.ok) {
      rejectButton.classList.add('hidden');
    }
  });
};

File: task-requests/details/script.js (hunk 6 above)
Comment (AnujChhikara) [reply task-requests/details/script.js:38]: To use that predefined function i have to either include the script file in the index.js file or make the script type module to import that function.

**Comment by AnujChhikara** [comment]
> coverage seems low

I have added the test coverage screenshot

File: mock-data/taskRequests/index.js [hunk 7]
```diff
@@ -339,7 +337,29 @@ const userInformation = {
     created_at: 1698684157040,
   },
 };
-
+const superUserData = {
```
Comment (vinit717) [inline mock-data/taskRequests/index.js:340]: use superUserDetails data which is already there in mock-data/users and use Ankush data instead of other people

File: task-requests/details/script.js [hunk 8]
```diff
@@ -13,15 +14,34 @@ const requestorSkeleton = document.querySelector(
 );
 
 const taskRequestContainer = document.getElementById('task-request-details');
+const requestDetailContainer =
+  document.getElementsByClassName('request-details');
 const taskContainer = document.getElementById('task-details');
 const toast = document.getElementById('toast_task_details');
-const rejectButton = document.getElementById('reject-button');
+// const rejectButton = document.getElementById('reject-button');
```
Comment (vinit717) [inline task-requests/details/script.js:21]: Why did you add a comment here?

File: task-requests/details/script.js (hunk 6 above)
Comment (vinit717) [reply task-requests/details/script.js:39]: Make it a module then as to call/self a function is already there

File: mock-data/taskRequests/index.js (hunk 7 above)
Comment (AnujChhikara) [reply mock-data/taskRequests/index.js:340]: so just replace this data with ankush data or import that data from mock-data/users

File: task-requests/details/script.js (hunk 6 above)
Comment (AnujChhikara) [reply task-requests/details/script.js:39]: we have to get that function like this if we make it moudle 
```javascript 
import { getIsSuperUser } from '../../applications/utils.js';
```
or we can just add this in the html head and not convert the file into module
```html
 <script src="/utils.js"></script>

File: mock-data/taskRequests/index.js (hunk 7 above)
Comment (vinit717) [reply mock-data/taskRequests/index.js:340]: yes Ankush data already been there

**Review by vinit717 — COMMENTED** [review]
Please write the test for the changes you made

File: __tests__/task-requests/task-requestDetails.test.js [hunk 9]
```diff
@@ -3,6 +3,60 @@ const {
...
+    expect(rejectButton).toBeNull();
+  });
+
+  it('Should render task status for non-super users', async function () {
+    const taskRequestStatus = await page.$(
+      '.requestors__container__list__status',
+    );
+    expect(taskRequestStatus).toBeTruthy();
+  });
+});
```
[the remark this answers is not in the document]
Comment (AnujChhikara) [reply __tests__/task-requests/task-requestDetails.test.js:59]: Okay , I was just following the way all tests are written previously . Data test id is not used by anyone that why i don't used it. Do I have to changed it?

[the remark this answers is not in the document]
Comment (vinit717) [reply __tests__/task-requests/task-requestDetails.test.js:59]: It is used recently by the folks after my suggestion you can have a look in codebase

File: mock-data/taskRequests/index.js (hunk 7 above)
Comment (vinit717) [reply mock-data/taskRequests/index.js:340]: I said you can import that data instead of writing it again

**Review by Achintya-Chatterjee — DISMISSED** [review]

**Review by vinit717 — COMMENTED** [review]
Can you put these changes behind feature flag

**Comment by vinit717** [comment]
Please update the video also showing both for feature flag and behind feature flag

**Review by vinit717 — APPROVED** [review]

**Review by Achintya-Chatterjee — APPROVED** [review]
