### PR TITLE
Hidden skeleton loader to/display error message Task not found

### LINKED ISSUE #925: Skeleton Loader on Task Details Page Stuck Forever for Missing or Failed API Response
### Issue Description

When navigating to the Task Details page, the skeleton loader is displayed while data is being fetched from the API. However, if the API returns an error (e.g., task not found or a server issue), the skeleton loader remains visible indefinitely. The user is not informed about the error, leading to confusion.

### Expected Behavior

If the API returns an error, the Task Details page should display an appropriate error message, such as:
- "Task not found" (for a 404 error).
- "Error fetching task details. Please try again later." (for other errors).
The skeleton loader should stop displaying once an error occurs.
### Current Behavior

When the API fails to fetch the task details:

- The skeleton loader remains visible indefinitely.
- No error message is displayed to the user.
### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
-  Go to this [task details page](https://dashboard.realdevsquad.com/task-requests/details/?id=voImPmPhqrL8Wa6x) 
-  I have put wrong task id in the params and observe that the skeleton loader remains visible indefinitely without showing an error message.

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.
### Additional Information

 - Backend Issue related to this [link](https://github.com/Real-Dev-Squad/website-backend/issues/2290)

### PR DESCRIPTION
**Pull request by Sibasundar103**
Date: 03 April 2025

Developer Name: @Sibasundar103 

---

## Issue Ticket Number  
- Closes #925

## Description  
This PR fixes the issue where the skeleton loader on the Task Details page remains indefinitely when the API response fails. Now, the loader is properly removed, and an error message is displayed when the API returns an error.  

## Changes:  
- Stopped the skeleton loader when the API fails.  
- Displayed appropriate error messages:  
  - "Task not found" for 404 errors.  
  - "Error fetching task details. Please try again later." for other errors.  
- Improved error handling in the API response flow.  

## Documentation Updated?  
- [ ] Yes  
- [x] No  

## Under Feature Flag  
- [x] Yes  
- [ ] No  

## Database Changes  
- [ ] Yes  
- [x] No  

## Breaking Changes  
- [ ] Yes  
- [x] No  

## Development Tested?  
- [x] Yes  
- [ ] No  

## Screenshots  

Before Fix
Screenshot 2025-04-04 012131

After Fix
Screenshot (51)

## Test Coverage  

Screenshot 2025-04-04 014326

## Additional Notes  
This fix ensures that users receive clear feedback when an API error occurs, preventing confusion caused by an indefinitely stuck skeleton loader. Let me know if any changes are required! 🚀

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,2 +1,3 @@
 node_modules/
-coverage/
\ No newline at end of file
+coverage/
```
Comment (Hariom01010) [inline .gitignore:2]: What is this .qodo file and why are we adding it to gitignore?

File: task-requests/details/script.js [hunk 2]
```diff
@@ -529,6 +539,9 @@ const renderTaskRequest = async () => {
     taskRequest = await fetchTaskRequest();
     isSuperUser = await getIsSuperUser();
     taskRequestSkeleton.classList.add('hidden');
+    if (!taskRequest) {
+      throw new Error('Task not found');
```
Comment (Hariom01010) [inline task-requests/details/script.js:543]: We are already doing error handling in fetchTaskRequest and showErrorMessage function. Do we need to throw this error here?

**Review by Hariom01010 — COMMENTED** [review]
Please address these comments

File: .gitignore [hunk 3]
```diff
@@ -1,2 +1,3 @@
...
+.qodo
```
Comment (Hariom01010) [inline .gitignore:3]: What is this .qodo file and why are we putting it in gitignore?

**Comment by Hariom01010** [comment]
Also resolve conflicts

File: __tests__/task-requests/task-requestDetails.test.js [hunk 4]
```diff
@@ -149,6 +149,31 @@ describe('Task request details page', () => {
...
+    await page.goto(
+      `${LOCAL_TEST_PAGE_URL}/task-requests/details/?id=dM5wwDdsfd9QsiTzi7eG7Oq5`,
+    );
+
+    await page.waitForNetworkIdle();
+
+    const errorElement = await page.$('[data-testid="error-message"]');
+
+    expect(errorElement).toBeNull();
+  });
```
Comment (RishiChaubey31) [inline __tests__/task-requests/task-requestDetails.test.js:176]: can you please write the test description more clear and simpler

File: task-requests/details/script.js [hunk 5]
```diff
@@ -543,6 +556,24 @@ const renderTaskRequest = async () => {
...
 };
 
+const showErrorMessage = (error) => {
+  let errorMessageDiv = document.querySelector('[data-testid="error-message"]');
+
+  if (!errorMessageDiv) {
+    errorMessageDiv = document.createElement('p');
+    errorMessageDiv.classList.add('error-message');
+    errorMessageDiv.setAttribute('data-testid', 'error-message');
+    errorMessageDiv.textContent = 'Task not found';
```
Comment (RishiChaubey31) [inline task-requests/details/script.js:566]: don't we have any constant file to store this error message

File: .gitignore (hunk 3 above)
Comment (Sibasundar103) [reply .gitignore]: fix

File: task-requests/details/script.js (hunk 2 above)
Comment (Sibasundar103) [reply task-requests/details/script.js:543]: Yes, the throw is helpful to prevent continuing with an invalid state.

File: task-requests/details/script.js (hunk 5 above)
Comment (Sibasundar103) [reply task-requests/details/script.js]: fix

File: __tests__/task-requests/task-requestDetails.test.js (hunk 4 above)
Comment (Sibasundar103) [reply __tests__/task-requests/task-requestDetails.test.js]: fix

File: .gitignore (hunk 3 above)
Comment (Hariom01010) [reply .gitignore:3]: what is fixed here?
image
I can still see the .qodo file . So the question i asked still remains unanswered

Comment (Sibasundar103) [reply .gitignore]: now i fix that

File: task-requests/details/script.js (hunk 2 above)
Comment (Hariom01010) [reply task-requests/details/script.js:543]: Replace the 'Task not found' with the constant you introduced in constants.js

**Review by Hariom01010 — APPROVED** [review]
All the changes suggested by me have been discussed/implemented. Thus, approving it

File: task-requests/constants.js [hunk 6]
```diff
@@ -52,7 +52,7 @@ const ErrorMessages = {
   UNAUTHENTICATED:
     'You are unauthenticated to view this section, please login!',
   UNAUTHORIZED: 'You are unauthrozed to view this section',
-  NOT_FOUND: 'Task Requests not found',
```
Comment (AnujChhikara) [inline task-requests/constants.js:55]: why do we changed this error message?

File: task-requests/details/script.js [hunk 7]
```diff
@@ -334,16 +334,26 @@ async function renderRequestors(taskRequest) {
...
+      data.approvedTo = approvedTo;
+      return data;
+    } else {
+      if (isDev) {
+        showErrorMessage(res.status);
+      }
+    }
+  } catch (e) {
+    console.log(e);
+  }
```
[the remark this answers is not in the document]
Comment (AnujChhikara) [reply task-requests/details/script.js:356]: @Sibasundar103 please look at this suggestion.

File: task-requests/details/script.js [hunk 8]
```diff
@@ -529,6 +539,9 @@ const renderTaskRequest = async () => {
     taskRequest = await fetchTaskRequest();
     isSuperUser = await getIsSuperUser();
     taskRequestSkeleton.classList.add('hidden');
+    if (!taskRequest) {
+      throw new Error(ErrorMessages.NOT_FOUND);
+    }
```
Comment (AnujChhikara) [inline task-requests/details/script.js:544]: What's the intention behind throwing this error here? Are we catching this somewhere, or is it meant to break the flow only?

File: task-requests/constants.js [hunk 9]
```diff
@@ -52,7 +52,7 @@ const ErrorMessages = {
...
+  NOT_FOUND: 'Task  not found',
```
Comment (AnujChhikara) [inline task-requests/constants.js:55]: also why double space ?

File: __tests__/task-requests/task-requestDetails.test.js [hunk 10]
```diff
@@ -147,6 +147,31 @@ describe('Task request details page', () => {
...
+      `${LOCAL_TEST_PAGE_URL}/task-requests/details/?id=dM5wwDdsfd9QsiTzi7eG7Oq5&dev=true`,
+    );
+
+    await page.waitForNetworkIdle();
+
+    const errorText = await page.$eval(
+      '[data-testid="error-message"]',
+      (el) => el.textContent,
+    );
+    expect(errorText).toBe('Task  not found');
```
Comment (AnujChhikara) [inline __tests__/task-requests/task-requestDetails.test.js:161]: same here why double space in the error message?

File: task-requests/constants.js (hunk 6 above)
Comment (Sibasundar103) [reply task-requests/constants.js:55]: i change the message bcz i want show i Task not found not Task requests not found

File: task-requests/constants.js (hunk 9 above)
Comment (Sibasundar103) [reply task-requests/constants.js]: now i fix this

File: __tests__/task-requests/task-requestDetails.test.js (hunk 10 above)
Comment (Sibasundar103) [reply __tests__/task-requests/task-requestDetails.test.js]: fixed

File: task-requests/details/script.js (hunk 8 above)
Comment (Sibasundar103) [reply task-requests/details/script.js:544]: This line is intentionally throwing an error to stop the rest of the code from executing if taskRequest is null or undefined. It's used as a control flow mechanism to exit early and signal that something went wrong

File: task-requests/constants.js (hunk 6 above)
Comment (AnujChhikara) [reply task-requests/constants.js:55]: why not 'Task Requests not found'?

File: task-requests/details/script.js (hunk 8 above)
Comment (AnujChhikara) [reply task-requests/details/script.js:544]: then why cannot we use return here?

File: task-requests/constants.js (hunk 6 above)
Comment (Sibasundar103) [reply task-requests/constants.js:55]: Because the Expected Behavior is
If the API returns an error, the Task Details page should display an error message "Task not found"

File: task-requests/details/script.js (hunk 8 above)
Comment (Sibasundar103) [reply task-requests/details/script.js:544]: We can't use return here because it would exit the function silently and skip the catch block. Using throw ensures the error is properly handled and the user sees an error message.

File: task-requests/constants.js (hunk 6 above)
Comment (AnujChhikara) [reply task-requests/constants.js:55]: but this page does not show task details, it show task-request details

File: task-requests/details/script.js (hunk 8 above)
Comment (AnujChhikara) [reply task-requests/details/script.js:544]: But we’re not showing any error in this catch block, just logging it. So does the throw really help here?

File: task-requests/constants.js (hunk 6 above)
Comment (Sibasundar103) [reply task-requests/constants.js]: now it show Task Requests not found

File: task-requests/details/script.js (hunk 8 above)
Comment (Sibasundar103) [reply task-requests/details/script.js:544]: the throw really not help here so i fixed it

**Review by AnujChhikara — COMMENTED** [review]
Hello @Sibasundar103  please update the test also , one test case is failing.

File: __tests__/task-requests/task-requestDetails.test.js [hunk 11]
```diff
@@ -147,6 +147,31 @@ describe('Task request details page', () => {
     );
     expect(descriptionTextValue).toBe(longDescription);
   });
+  it('Displays "Task Requests not refound" When the task ID is invalid and dev mode is enabled', async function () {
```
Comment (AnujChhikara) [inline __tests__/task-requests/task-requestDetails.test.js:150]: typo in "Task Requests not refound"

File: __tests__/task-requests/task-requestDetails.test.js [hunk 12]
```diff
@@ -147,6 +147,31 @@ describe('Task request details page', () => {
...
+
+    const errorText = await page.$eval(
+      '[data-testid="error-message"]',
+      (el) => el.textContent,
+    );
+    expect(errorText).toBe('Task Requests not found');
+  });
+
+  it('Does not show "Task Requests not found" message when dev mode is disabled', async function () {
+    await page.goto(
```
Comment (AnujChhikara) [inline __tests__/task-requests/task-requestDetails.test.js:165]: can we start the test description with should not show or should show for both of your tests, like the other ones? just to keep things consistent

File: .gitignore
Comment (AnujChhikara) [inline .gitignore:1]: It looks like the coverage/ line in .gitignore was removed and added back—was this intentional? If not, could you kindly revert it?

File: task-requests/details/script.js [hunk 13]
```diff
@@ -543,6 +556,24 @@ const renderTaskRequest = async () => {
   }
 };
 
+const showErrorMessage = (error) => {
```
Comment (AnujChhikara) [inline task-requests/details/script.js:559]: Currently, the `error` parameter is not being used in the `showErrorMessage` function. It might be useful to implement it for displaying more specific error messages. You can refer to how it's handled on other pages

**Comment by AnujChhikara** [comment]
Hello @Sibasundar103 , could you please attach a screenshot of how this will appear on a mobile screen, if possible?

**Comment by Sibasundar103** [comment]
> Hello @Sibasundar103 , could you please attach a screenshot of how this will appear on a mobile screen, if possible?

Screenshot 2025-04-20 220235

File: task-requests/details/script.js [hunk 14]
```diff
@@ -543,6 +556,24 @@ const renderTaskRequest = async () => {
   }
 };
 
+const showErrorMessage = () => {
```
Comment (AnujChhikara) [inline task-requests/details/script.js:559]: Can we please make this function more generic. Currently, it always shows "Task requests not found" regardless of the actual error. Instead, we should pass the error or status code and display an appropriate message based on that.

File: task-requests/details/script.js [hunk 15]
```diff
@@ -543,6 +556,26 @@ const renderTaskRequest = async () => {
   }
 };
 
+const showErrorMessage = (error) => {
+  let errorMessageDiv = document.querySelector('[data-testid="error-message"]');
```
Comment (AnujChhikara) [inline task-requests/details/script.js:560]: what will happen if we already have the errorMessageDiv?

Comment (Sibasundar103) [reply task-requests/details/script.js]: i remove this line

File: task-requests/details/style.css [hunk 16]
```diff
@@ -571,6 +571,14 @@ p:hover {
...
 }
 
+.error-message {
+  place-items: center;
+  height: 100vh;
+  width: 100vw;
+  position: fixed;
+  left: 0;
+  text-align: center;
+}
```
Comment (MayankBansal12) [inline task-requests/details/style.css:581]: from the css added, the items should be center aligned both vertically and horizontally, but in the screenshot added, it appears to be on top. Can you please update the screenshot or correct me if I am missing something here?

Comment (Sibasundar103) [reply task-requests/details/style.css]: now i update the code and screenshot also

Comment (Sibasundar103) [reply task-requests/details/style.css]: Screenshot 2025-04-26 144444

**Review by iamitprakash — APPROVED** [review]
