### PR TITLE
fix: Wong error message for Unauthenticated user

### LINKED ISSUE #810: Fix Unauthenticated Users receiving "Unexpected error occurred" Instead of Authentication Error Message at Task Requests Page
### Issue Description
When unauthenticated users attempt to access the task-requests page of the dashboard site, they are presented with an "Unexpected error occurred" message. However, the correct behaviour should be to inform the user that they are unauthenticated and prompt them to log in.

### Expected Behavior
Unauthenticated users should receive the following message when trying to access the task-requests page of the dashboard site: "You are unauthenticated to view this section, please login!".

### Current Behavior
Unauthenticated users are currently shown a generic server error message: "Unexpected error occurred," which does not accurately reflect the authentication issue.

### Screenshots
Screenshot 2024-09-02 at 8 59 29 PM

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Log out of the application (or access the task-requests page of the dashboard site without logging in)
2. Attempt to access the dashboard.
 [Try by clicking here](https://dashboard.realdevsquad.com/task-requests/)

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information
This issue could lead to confusion among users as the current error message does not provide clear guidance on the actual problem, which is the need for authentication.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by VaibhavSingh8**
Date: `03 Sep 2024`

Developer Name: Vaibhav Singh

---

## Issue Ticket Number 

- Closes #810 
## Description

Fixed the wrong error message being displayed for unauthenticated users at the [dashboard site/task-requests](https://dashboard.realdevsquad.com/task-requests) page from "Unexpected error occurred" to correct respective authentication error.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-09-04 at 12 35 39 AM

</details>

## Test Coverage
Test Coverage only for task-requests: All tests passed
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-09-04 at 12 31 36 AM

</details>

### CODE REVIEW

File: task-requests/script.js [hunk 1]
```diff
@@ -60,22 +60,25 @@ async function getTaskRequests(query = {}, nextLink) {
 
     if (res.status === 401) {
       showMessage('ERROR', ErrorMessages.UNAUTHENTICATED);
-      return;
+      return { data: [] };
```
Comment (iamitprakash) [inline task-requests/script.js:63]: did you check via unit test

**Review by iamitprakash — CHANGES_REQUESTED** [review]

File: task-requests/script.js (hunk 1 above)
Comment (VaibhavSingh8) [reply task-requests/script.js:63]: Yes sir, I have attached the test results

**Review by iamitprakash — APPROVED** [review]
