### PR TITLE
Fix/remove outdated fields

### LINKED ISSUE #893: Enhance Create Task Form(according to new requirements)
# Enhance Create Task Form

## Issue Description
Enhance the create task form by removing specific fields and adding new ones as per the updated requirements.

## Current Behavior
The current create task form includes the following fields:
image

## Expected Behavior
The create task form should be updated as follows:

### Fields to be added:
- Skills (multi-select, similar to label selection in Jira / assigning labels to PR on GitHub)
- Assigned to (optional, search user + autocomplete)

### Fields to be removed:
- Task Level
- Category
- Level
- Feature URL
- Feature/Group

All other existing fields should be retained.

After following changes it should look like this ( Not functional right now )

create-task-form2

### when ` status ` is ` available `
 - Do not show ` Assigned to ` feild 
 - Do not show ` Ends on ` feild

## Reproducibility
- [x] This issue is reproducible
- [ ] This issue is not reproducible

## Steps to Reproduce
1. Navigate to the create task form
2. Observe the current fields present in the form
3. Compare with the new requirements

## Severity/Priority
- [ ] Critical
- [ ] High
- [x] Medium
- [ ] Low

## Additional Information
The new 'Skills' field should allow multi-select functionality. 
The 'Assigned to' field should right now only be search with autocomplete functionality.

## Steps to complete this task 
 - [ ]  Add `Skills` feild 
 - [ ]  Remove unecessary feilds
 - [ ] Modify `Assiged to ` field to match the requirements
 
## Checklist
- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by sunilk429**
## Developer Name: Sunil Kumar 

---

## Issue Ticket Number

- closes #893 
## Description

The following fields needs to be removed according to new requirements
`featureUrl`
`feature/group` radio button
Task level section
`category`
`level` 
### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [x] Yes
- [ ] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

imageimage

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

image
image

### CODE REVIEW

File: task/script.js [hunk 1]
```diff
@@ -192,28 +216,32 @@ taskForm.onsubmit = async (e) => {
     delete dataToBeSent.endsOn;
   }
 
-  if (status === 'AVIALABLE') {
+  if (status === 'AVAILABLE') {
```
Comment (iamitprakash) [inline task/script.js:219]: Don’t we have any enum available here

**Review by iamitprakash — CHANGES_REQUESTED** [review]
Where is test

File: task/script.js (hunk 1 above)
Comment (sunilk429) [reply task/script.js:219]: Nope, I couldn't find any

File: __tests__/tasks/task-dev-dependency.test.js [hunk 2]
```diff
@@ -0,0 +1,106 @@
+const API_BASE_URL = 'https://api.realdevsquad.com';
```
Comment (vinit717) [inline __tests__/tasks/task-dev-dependency.test.js:1]: I think we already have defined the based URL in the test config can you please check

File: __tests__/tasks/task-dev-dependency.test.js
Comment (vinit717) [inline __tests__/tasks/task-dev-dependency.test.js:1]: Use data test id instead of classes and id

**Review by vinit717 — CHANGES_REQUESTED** [review]

File: __tests__/tasks/task-dev-dependency.test.js (hunk 2 above)
Comment (sunilk429) [reply __tests__/tasks/task-dev-dependency.test.js:1]: I have checked, I couldnt find can you tell me which file? 
Also if you check task-dependency.test.js also has const API_BASE_URL = 'https://api.realdevsquad.com'; let me know if it can be replaced

File: __tests__/tasks/task-dev-dependency.test.js
Comment (sunilk429) [reply __tests__/tasks/task-dev-dependency.test.js:1]: I can but this code has later to be removed anyways, why should we update index.html and add data test id's, id's and classes seems fine, isn't it?

File: __tests__/tasks/task-dependency.test.js [hunk 3]
```diff
@@ -15,80 +16,159 @@ describe('Input box', () => {
...
+
+        if (mockResponses[url]) {
+          interceptedRequest.respond({
+            status: 200,
+            contentType: 'application/json',
+            headers: {
+              'Access-Control-Allow-Origin': '*',
+            },
+            body: JSON.stringify(mockResponses[url]),
+          });
```
[the remark this answers is not in the document]
Comment (sunilk429) [reply __tests__/tasks/task-dependency.test.js:39]: > Can you please check if this if statement getting executed?

Just did refactoring and its working though

**Review by yesyash — APPROVED** [review]

File: task/script.js (hunk 1 above)
Comment (prakashchoudhary07) [reply task/script.js:221]: Then please create one and use it

Comment (sunilk429) [reply task/script.js]: > Then please create it and use it

Did it, please do review

**Review by yesyash — APPROVED** [review]

**Review by iamitprakash — APPROVED** [review]
